### PR TITLE
desc_get_built() reads multiples lines

### LINKED ISSUE #145: `get_built()` fails if `Built` is not a single line

### PR DESCRIPTION
**Pull request by seankross**
Fixes #145

### CODE REVIEW

File: R/built.R [hunk 1]
```diff
@@ -1,8 +1,9 @@
 
 idesc_get_built <- function(self, private) {
-  built <- unname(self$get("Built"))
+  built <- gsub("\\n", "", unname(self$get("Built")))
   if (is.na(built)) stop("No ", sQuote('Built'), " field found")
-  built <- as.list(strsplit(built, "; ")[[1L]])
+  built <- lapply(as.list(strsplit(built, "; ")[[1L]]), gsub,
```
Comment (krlmlr) [inline R/built.R:5]: What do we need `lapply()` here for if we didn't need it before? I _think_ we still should have `length(built) == 1` even for multi-line fields?

Can we instead use `strsplit(built, "^[[:space:]]*;[[:space:]]+")[[1L]]` ?

**Review by krlmlr — COMMENTED** [review]
Thanks! I like your test case, could we simplify the logic?

File: R/built.R (hunk 1 above)
Comment (seankross) [reply R/built.R:5]: Splitting on leading and trailing space does not produce a list of length 4. Also I just now realized `stringr::str_trim` is already used in this package, so I replaced `gsub` in the `lapply`. Leading whitespace is introduced because of the new line. I'll commit that change if this implementation is okay with you. Reprex below:

```
library(devtools)
load_all()
self <- description$new(test_path("D16"))

built <- gsub("\\n", "", unname(self$get("Built")))
if (is.na(built)) stop("No ", sQuote('Built'), " field found")
built <- lapply(as.list(strsplit(built, "; ")[[1L]]), str_trim)
if (length(built) != 4L) {
  stop(sQuote('Built'), " field is corrupted")
}
names(built) <- c("R", "Platform", "Date", "OStype")
built[["R"]] <- R_system_version(sub("^R ([0-9.]+)", "\\1", built[["R"]]))
built

# $R
# [1] ‘3.4.1’
# 
# $Platform
# [1] "x86_64-apple-darwin15.6.0"
# 
# $Date
# [1] "2017-09-14 20:30:19 UTC"
# 
# $OStype
# [1] "unix"

built <- gsub("\\n", "", unname(self$get("Built")))
if (is.na(built)) stop("No ", sQuote('Built'), " field found")
built <- as.list(strsplit(built, "^[[:space:]]*;[[:space:]]+")[[1L]])
if (length(built) != 4L) {
  stop(sQuote('Built'), " field is corrupted")
}

# Error: ‘Built’ field is corrupted
```

**Comment by krlmlr** [comment]
Could be as simple as replacing `$get()` with `$get_field()` :

``` r
writeLines(
  c(
    "Type: package",
    "Built: R 3.4.1; x86_64-apple-darwin15.6.0;\n  2017-09-14 20:30:19 UTC; unix"
  ),
  "DESCRIPTION"
)

desc <- desc::desc(file = "DESCRIPTION")

desc$get("Built")
#>                                                                  Built 
#> "R 3.4.1; x86_64-apple-darwin15.6.0;\n  2017-09-14 20:30:19 UTC; unix"
desc$get_field("Built")
#> [1] "R 3.4.1; x86_64-apple-darwin15.6.0; 2017-09-14 20:30:19 UTC; unix"
```

<sup>Created on 2024-08-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by gaborcsardi** [comment]
Thank you!
